voiceflow/general-runtime

lib/controllers/interact.ts
lib/services/chips/index.ts
lib/services/chips/utils.ts
lib/services/dialog/index.ts
lib/services/dialog/utils.ts
lib/services/index.ts
lib/services/runtime/handlers/interaction.ts
package.json
tests/lib/controllers/interact.unit.ts
tests/lib/services/dialog/fixture.ts
tests/lib/services/dialog/index.unit.ts
yarn.lock

so what I wanted to do here:
To show a chip for an intent, we show the utterance with the minimal number of potential slots: 
"I want pizza" over "I want a {small} pizza"
For dialog management, show up to 3 choices to fill in the slots. So if it asks "what size do you want your pizza?"
the chips you would get are "small" "medium" and "large"
this behavior used to be handled in the frontend here, but has now been enhanced:
https://github.com/voiceflow/creator-app/blob/859c14317c5a92bf258457dfe9724dd29acd1c64/src/pages/Prototype/PrototypeTool/utils/intent.ts

feat: chips

---

lib/services/dialog/index.ts
lib/services/dialog/utils.ts
lib/services/nlu/index.ts
lib/services/nlu/nlc.ts
lib/services/nlu/utils.ts
package.json
tests/lib/services/dialog/index.unit.ts
yarn.lock

The reason why this works is because we already have dialog management built into the NLC:
https://github.com/voiceflow/natural-language-commander/blob/master/src/NaturalLanguageCommander.ts#L222
This was already being used by the FE:
https://github.com/voiceflow/creator-app/blob/master/src/pages/Prototype/PrototypeTool/Dialog.ts#L147
To test this, just go to the NLU `predict` function and make it throw an error from from the axios call every time (comment out the code, throw an error, and ignore dependencies)
turns out we had a bug in the NLC the whole time
https://github.com/voiceflow/natural-language-commander/commit/14dd8094200a519879800dc529315c46041b1f3d

feat: nlc dm

---

.depcheckrc
package.json
yarn.lock

This package was using the npm package `crypto` (which is a proxy, has no actual code) instead of the builtin node library

chore(deps): remove crypto dependency

---

lib/services/runtime/handlers/speak.ts

`test = "{test_nested}"`
and if we put that into a speak block with `{test}` and have it display the value of `{test_nested}` we want it to replace twice?
so if we want to pass in a variable that contains a string with "variables" you would technically need to replace it twice. This is an edge case. I think in the future we make build this into the replaceVariables function.
Although I'm not sure if this is the base behavior, might need some further discussion. While we allow it to go into a depth of 2 here - is there an actual limit we want to enforce.

fix: nested replace (CORE-000)

---

.circleci/config.yml

**Fixes or implements CORE-4986**
Added build failures notification on master branch and move slack notifications to the orb

ci(circleci): added failure and deploy notifications (CORE-4986)

---

lib/services/dialog/index.ts

**Fixes or implements CORE-5164**
The bug in the ticket is that our built-in Number slot type is filling with entire utterances, not just the number value within those utterances. The reason this happens is because LUIS matches the amount entity with a value of type `number` instead of `string`. The code in this PR assumed entity.value was always a `string`, so it would throw an error when it tried to called .replace() on a `number`. This lead to it going down the wrong path and putting the entire utterance into the slot value.
- [ ✅  ] title of PR reflects the branch name
- [ ✅  ] all commits adhere to conventional commits
- [ ✅  ] all the dependencies are upgraded

fix: stop number slot from being filled with entire utterances (CORE-5164)

---

lib/services/state/index.ts

we want to give consumers the same thing we do on alexa and google: if they have an existing state but finished their previous session (stack empty) then just populate the stack again and persist their variables + storage

fix: account for empty stack (CORE-000)

---

lib/services/runtime/handlers/state/index.ts
lib/services/runtime/handlers/state/oneShot.ts

So there is this edge case if the user sends a text request when the stack hasn't loaded yet or their session is not initialized. That means that they will be on the start block.
What we do is see if there are any intent blocks or command blocks that can handle their request. If not, just proceed down the start block as normal, and consider the request handled.
We already use this pattern for alexa

feat: one shot intent handler (CORE-000)

---

.env.test
backend/serviceManager.ts
config.ts
lib/clients/dataAPI.ts
lib/clients/index.ts
lib/controllers/interact.ts
lib/services/runtime/index.ts
lib/services/state/index.ts
package.json
tests/lib/clients/dataAPI.unit.ts
tests/lib/controllers/interact.unit.ts
tests/lib/services/runtime/index.unit.ts
tests/lib/services/state/index.unit.ts
types.ts
yarn.lock

**Fixes or implements CORE-5221**
Allows for API key support when hitting the interact endpoint.
For req with origin voiceflow.com, dataAPI uses server-data-api. Otherwise, it uses creator-api and attaches the API key that the user request should have. The API key could come from an environment variable, or overrode by one in the request header.
This keeps server-data-api as our internal interface to the db and creator-api as the external interface protected by auth_vf or api-key.
DataAPI is now a class instead of a function, which creates all three APIs if it has the information to. When an API call needs to be made, get() is called, which takes in the authorization (API key or auth_vf) and the origin of the request and determines which API it should make the call to.
⚠️⚠️⚠️ …

feat: API Key Verification (CORE-5221)

---

.env.test
backend/api/routers/interact.ts
config.ts
lib/clients/index.ts
lib/clients/rateLimiter.ts
lib/clients/redis.ts
lib/middlewares/index.ts
lib/middlewares/rateLimit.ts
lib/services/index.ts
lib/services/rateLimit.ts
package.json
tests/lib/clients/rateLimiter.unit.ts
tests/lib/middlewares/rateLimit.unit.ts
tests/lib/services/rateLimit.unit.ts
tests/server/interact.unit.ts
types.ts
typings/voiceflow__verror.d.ts
yarn.lock

**Fixes or implements CORE-5291**
Rate limit requests for sdk users
using rate-limiter-flexible and redis as storage (to support multiple instance of this service running in the cluster). 
public limiter - for limiting creator-app or users trying to fake creator-app's origin without auth key (limits by versionID)
private limiter - for limiting auth keys
⚠️⚠️⚠️ NEW ENV VARS TO ADD ⚠️⚠️⚠️
```
REDIS_CLUSTER_HOST # required
REDIS_CLUSTER_PORT # required
// 1000 request per minute
RATE_LIMITER_POINTS_PUBLIC
RATE_LIMITER_DURATION_PUBLIC
// 500 requests per minute
RATE_LIMITER_POINTS_PRIVATE
RATE_LIMITER_DURATION_PRIVATE
```
Defaults are arbitrary and open to change. As a scale, currently our prod alexa-runtime is handling an average of 400 requests/min.

feat: rate limiting (CORE-5291)

---

lib/clients/dataAPI.ts
lib/controllers/interact.ts
lib/services/state/index.ts
tests/lib/clients/dataAPI.unit.ts

If we check for origin in the rate limiter middleware, there's no point to do the checkin dataAPI, since it is assume any call that comes in is already validated. Also did a cleaner pattern for `creatorDataApi` with less instance variables.
For deciding whether to use `remoteAPI` or `creatorDataApi`: if the user tries to make an authenticated call, just use `creatorDataApi`

fix: remove origin requirement (CORE-000)

---

lib/controllers/interact.ts
lib/middlewares/rateLimit.ts
lib/services/dialog/index.ts
lib/services/index.ts
lib/services/runtime/handlers/noMatch.ts
lib/services/runtime/handlers/speak.ts
lib/services/runtime/init.ts
lib/services/slots/index.ts
lib/services/tts/index.ts
package.json
tests/lib/controllers/interact.unit.ts
tests/lib/services/dialog/index.unit.ts
tests/lib/services/slots/index.unit.ts
yarn.lock

**Fixes or implements CORE-4839 and CORE-4840**
Implements NATO/APCO slot type in a new handler, SlotsService. There are also some additions of `type: SpeakType.MESSAGE` to SpeakTraces as type is no longer optional.
- SlotsService combines the NATO/APCO words identified by LUIS together with their first letters. entity.rawValue contains the words to parse and entity.value will store the result. Ex: rawValue: [['November'],['India'],['Charlie'],['Echo']] -> value: 'NICE'. The only exceptions to taking the first letter of the strings is '00' and '000', these stay the same.
- Unit tested the SlotService handler
| general-service | [link](https://github.com/voiceflow/general-service/pull/57) |
| luis-authoring-service …

feat: implement NATO/APCO slot types (CORE-4839)

---

lib/controllers/interact.ts
lib/services/filter/index.ts
lib/services/filter/utils.ts
lib/services/index.ts
package.json
tests/lib/clients/dataAPI.unit.ts
tests/lib/controllers/interact.unit.ts
tests/lib/services/filter/fixture.ts
tests/lib/services/filter/index.unit.ts
types.ts
yarn.lock

**Fixes or implements CORE-5334**
Moving SSML sanitization logic from `runtime-client-js` to `general-runtime` so that we avoid re-implementing the sanitization logic for the SDK in other languages.
Adding a handler `Filter` on `general-runtime`. The single responsibility of this handler is to perform filtering or sanitization of the data produced by other handlers. 
Extending the `TurnBuilder.resolve(...)` call to accept a `config` object. The `config` object can be used to modify the behaviour of not only the `Filter` handler, but also any handler behaviours in the future. 
**Unrelated change:** Fix some asynchronous unit tests that were broken, causing the rest of the tests to not run and causing the coverage of `general-runtime` to drop from 65% to 35%. 
None
Merge in the related PR …

feat: passing config object into general-runtime handlers (CORE-5334)

---

lib/clients/remoteDataAPI.ts
lib/controllers/interact.ts
lib/services/nlu/index.ts
lib/services/runtime/handlers/command.ts
lib/services/runtime/handlers/event/index.ts
lib/services/runtime/handlers/index.ts
lib/services/runtime/handlers/interaction.ts
lib/services/runtime/handlers/noMatch.ts
lib/services/runtime/handlers/trace.ts
lib/services/runtime/types.ts
lib/services/state/cacheDataAPI.ts
package.json
tests/lib/services/runtime/handlers/capture.unit.ts
tests/lib/services/runtime/handlers/event/index.unit.ts
tests/lib/services/runtime/handlers/interaction.unit.ts
tests/lib/services/runtime/handlers/trace.unit.ts
tests/lib/services/runtime/types.unit.ts
types.ts
yarn.lock

to-test:
- import [test trace block.zip](https://github.com/voiceflow/general-runtime/files/6111400/test.trace.block.zip)
manual tests performed:
- default path (doesn't stop)
- inline events (event1, event2)
- global jump events (event3, event4)
- global push event (help)
- hit intent (travel_intent) from trace block
- hit command (second_flow) from trace block

feat: trace handler (CORE-5344)

---

lib/services/slots/index.ts
lib/services/slots/natoApco.ts
package.json
tests/lib/services/slots/fixture.ts
tests/lib/services/slots/index.unit.ts
yarn.lock

**Fixes or implements CORE-5346**
Slot Service will now parse the NATO/APCO entities against the original string and see if there are any numbers before or between them, then add those in together. It also accounts for 'to' -> 2 and 'for' -> 4 if they are near other NATO/APCO entities.
- Created a function to process the query string into a list of QueryWords, which contain information for identifying undetected NATO/APCO words.
- Rewrite logic for natoApcoConverter
- Update unit tests
| general-types | [link](https://github.com/voiceflow/general-types/pull/56) |
| general-service     | [link](https://github.com/voiceflow/general-service/pull/70) |
- [ ✅  ] title of PR reflects the branch name
- [ ✅  ] all commits …

fix: nato bug fix (CORE-5346)

---

lib/services/runtime/index.ts
tests/lib/services/runtime/index.unit.ts

**Fixes or implements CORE-XXX**
Add a new builtin `intent_confidence` variable and update it on each intent reauest.
https://github.com/voiceflow/creator-app/pull/3133

feat: add intent-confidence var (CORE-5398)

---

backend/docs/openapi.yaml
lib/services/runtime/handlers/_v1.ts
lib/services/runtime/index.ts
lib/services/runtime/types.ts
tests/lib/services/runtime/handlers/_v1.unit.ts

For the prototype tool, if we want to stop on all trace/action blocks - there's no way to do it because we actually don't know all the types beforehand. So we actually need a separate command.
The other way we could do this is to have a special keyword like `any` in the stopTypes.

fix: stop all (CORE-000)

---

backend/docs/openapi.yaml
lib/services/filter/index.ts
tests/lib/services/filter/index.unit.ts

**Fixes or implements VF-723**
Add excludeTypes config that by default filters out debugging types that only the prototype tool needs.
stripSSML is also "true" by default, unless explicitly false.
Going to update creator-app to have these parameters filled out.

feat: smarter default filters (VF-723)

---

lib/middlewares/rateLimit.ts

So the problem is that with vfcli is origin on dev is naturally set to `https://creator-dev-<NAME>.development.voiceflow.com/`.
However if you are doing any kind of frontend work you are going to run it locally: `https://creator-local.development.voiceflow.com:3002`. So now we have two origins to account for. This is a temporary hack, but if you think there is a cleaner way of doing this @leartgjoni-voiceflow let me know.

fix: rate limit origin (VF-000)

---

.env.e2e
backend/serviceManager.ts
config.ts
lib/middlewares/rateLimit.ts
types.ts

**Fixes or implements VF-298**
add a flag `DISABLE_ORIGIN_CHECK` to be used when running `e2e` tests
needed for https://github.com/voiceflow/creator-app/pull/3229

test: add flag to disable origin check for e2e tests (VF-298)

---

backend/docs/openapi.yaml
lib/controllers/stateManagement/index.ts
lib/services/stateManagement.ts
tests/lib/services/stateManagement.unit.ts
tests/server/state.unit.ts

**Fixes or implements [VF-951](https://voiceflow.atlassian.net/browse/VF-951?atlOrigin=eyJpIjoiMGYyYjhlN2I4MjgwNDUxMzkyOWJiZWYxNmJiMTdkNTYiLCJwIjoiaiJ9)**
Supports returning the state in addition to the trace in responses on the state API*.
\* only one route, [`POST` `/state/{versionID}/user/{userID}/interact`](https://www.voiceflow.com/api/dialog-manager#operation/stateInteract)
Checks for a `verbose` boolean query parameter, and if true will return the verbose response.
Default behavior has not changed.

feat: support verbose responses from state API (VF-951)

---

backend/api/routers/state.ts
backend/docs/openapi.yaml
lib/controllers/stateManagement/index.ts
tests/lib/controllers/stateManagement.unit.ts
tests/server/state.unit.ts

So several users using the State API have asked about how they can use an external service to update the user's runtime variables. Right now the only way is to GET the user's state, and then modify the variable, and then PUT it back in.
I'm just condensing this into a single endpoint. I totally understand that there is a way to atomically merge objects with the mongo syntax, and that this has a slight race condition, but it is pretty clean and should work for the time being.
I've tested it a few times - interesting edge case being if the user has no state at all, and we update the variables, the `interact` still works fine.
Looking for feedback on the endpoint and presentation of this.
| ------------------- | ----------- …

feat: patch variables (VF-000)

---

lib/services/runtime/index.ts
tests/lib/services/runtime/index.unit.ts

**Fixes or implements VF-1278**
The built in timestamp variable was not being populated with most recent changes in the prototype test.
See behaviour:
https://user-images.githubusercontent.com/19617248/125843477-8af14baa-04ea-48f7-9aa1-bde908ce2d05.mp4

feat: populate timestamp on each request (VF-1278)

---

lib/services/runtime/index.ts
lib/services/runtime/types.ts
tests/lib/services/runtime/index.unit.ts

**Fixes or implements VF-1162**
Add a global `last_utterance` variable.
- voiceflow/google-runtime#121
- voiceflow/creator-app#3804

feat: add `last_utterance` global variable (VF-1162)

---

config.ts

**Fixes or implements VF-1399**
Loosen the response timeout from 10 seconds to 30 seconds, temporarily.
If you really don't want to have this time increased set the `ERROR_RESPONSE_MS` variable to `10000`.
- #161

fix: loosen response timeout from 10s to 30s (VF-1399)

---

config.ts

**Fixes or implements VF-1549**
Reduce the default timeout from 30s to 10s.
- voiceflow/alexa-runtime#186
- voiceflow/google-runtime#127
- voiceflow/general-runtime#164

fix: set default timeout time to 10s (VF-1549)

---

lib/services/analytics.ts
lib/services/index.ts
lib/services/interact.ts
lib/services/runtime/index.ts
tests/lib/services/analytics.unit.ts
tests/lib/services/interact.unit.ts

**Fixes or implements VF-1593**
So originally the analytics was part of the runtime handler, and they would never be hit if the DM handler decided to exit early and skip the next handler in the sequence. 
Now it is in its own dedicated handler. I didn't add it at the very end because we don't want the trace to get polluted by the TTS MP3 and have too much data stored.

fix: dm analytics (VF-1593)

---

lib/services/runtime/handlers/event/index.ts
lib/services/runtime/handlers/interaction.ts

**Fixes or implements VF-1765**
This is a really legacy issue coming to bite us in the ass. So a long time ago every single interaction step contained the specific mappings from slot to variables. (So you could choose to not map certain ones)
But that's long gone and for backwards compatibility we kept the system. (context.mappings) and they get automatically declared in the compiler in general-service.
The new buttons step compiles into an interaction step but we didn't include these implicit mappings.
I think the fix going forward if there are no mappings, is to just turn every entity/slot in the intent into a variable.

fix: entities mapping (VF-1765)

---

lib/services/state/cacheDataAPI.ts
package.json
runtime/lib/DataAPI/creatorDataAPI.ts
runtime/lib/DataAPI/localDataAPI.ts
runtime/lib/DataAPI/serverDataAPI.ts
runtime/lib/DataAPI/types.ts
tests/lib/clients/dataAPI.unit.ts
tests/lib/clients/index.unit.ts
tests/lib/clients/metrics.unit.ts
tests/lib/clients/mongodb.unit.ts
tests/lib/clients/remoteDataAPI.unit.ts
tests/lib/services/analytics.unit.ts
tests/lib/services/runtime/handlers/repeat.unit.ts
tests/lib/services/runtime/index.unit.ts
tests/lib/services/state/cacheDataAPI.unit.ts
tests/runtime/lib/DataAPI/creatorDataAPI.unit.ts
tests/runtime/lib/DataAPI/localDataAPI.unit.ts
tests/runtime/lib/DataAPI/serverDataAPI.unit.ts
tests/runtime/lib/Handlers/if.unit.ts
yarn.lock

**Fixes or implements VF-1685**
Call server-data-api to unhash legacy skill id
memoized call to avoid network call for popular skills
Dependent on https://github.com/voiceflow/server-data-api/pull/70 getting merged first
| alexa-runtime | [link](https://github.com/voiceflow/alexa-runtime/pull/195/files) |
| google-runtime     | [link](https://github.com/voiceflow/google-runtime/pull/135/files) |

feat: unhashVersionID in dataAPI (VF-1685)

---

runtime/lib/Handlers/api/index.ts
tests/runtime/lib/Handlers/api.unit.ts

Trying to have consistency on local runtimes vs custom-api server.
We added this headers thing to custom-api awhile back: https://github.com/voiceflow/custom-api/pull/55
but it is not the case for calling axios directly from the runtime. To maintain consistency and make debugging easier, I decided to wrap it here.

fix: declare user agent (VF-000)

---

lib/services/interact.ts
lib/services/runtime/index.ts
lib/services/runtime/types.ts
lib/services/state/index.ts
runtime/lib/Context/types.ts
tests/lib/services/interact.unit.ts
tests/lib/services/runtime/index.unit.ts

**Fixes or implements VF-2153**
Made user_id variable reflect the UserID passed in the network request for state api requests 
(see: https://www.voiceflow.com/api/dialog-manager#operation/stateInteract ).
For first time UserIDs, the `user_id` variable is set in the initial generation of the context. 
See lib/services/state/index.ts -> StateManager -> generate.
For existing userIds to be able to access the `user_id`, the addition of the variable is done in the case of a `LAUNCH` request. I thought it would be overkill to set it for every state api request, so a reset for any user will add the ability to use the `user_id` variable.

feat: Set user_id to UserId for state api calls (VF-2153)

---

config.ts
runtime/lib/Runtime/Store/index.ts
runtime/lib/Runtime/utils/variables.ts

After talking to a client, it appears that immer may cause drastic slowdowns when performing operations on very large objects.  Immer takes a lot of time and memory to create proxies for such a big object
Instead just use traditional object destructuring techniques to preserve immutability. 
We can consider removing immer entirely.

feat: reduce immer use (VF-000)

---

.circleci/config.yml
Dockerfile
Dockerfile.e2e

**Fixes or implements VF-2065**
upgrade to node16 during the build process and on runtime
upgrading the executors to node 16 on our orb
deep Test this before merge

feat: upgrade to Node.js v16 (VF-2065)

---

.circleci/config.yml

**Fixes or implements VF-2213**
manual approval for e2e and disabled sonar on creator-app
the e2e will require manual approval only for all the branches except master even if they are marked as draft.

ci: e2e manual approval

---

lib/services/dialog/utils.ts
lib/services/runtime/handlers/_v1.ts
lib/services/runtime/handlers/capture.ts
lib/services/runtime/handlers/command.ts
lib/services/runtime/handlers/interaction.ts
lib/services/runtime/handlers/state/oneShot.ts
lib/services/runtime/handlers/state/preliminary.ts
lib/services/runtime/handlers/state/stream.ts
runtime/lib/Runtime/cycleHandler.ts
runtime/lib/Runtime/index.ts
tests/lib/services/dialog/utils.unit.ts
tests/lib/services/runtime/handlers/_v1.unit.ts
tests/lib/services/runtime/handlers/capture.unit.ts
tests/lib/services/runtime/handlers/command.unit.ts
tests/lib/services/runtime/handlers/interaction.unit.ts
tests/lib/services/runtime/handlers/state/preliminary.unit.ts
tests/lib/services/runtime/handlers/state/stream.unit.ts
tests/runtime/lib/Runtime/cycleHandler.unit.ts
tests/runtime/lib/Runtime/index.unit.ts

Previously, there were two states: `Action.RESPONSE` and `Action.REQUEST`
When we hit a choice/interaction/prompt/capture node, if it was `Action.RESPONSE` we would stop the execution and wait for the user to give a request. If we were on the same node but it was `Action.REQUEST` we would take the user request and actually compare it against the ports/commands, update the action to `Action.RESPONSE` and continue the execution.
Some problems with that model:
1. handlers had to declare `setAction(Action.RESPONSE)` explicitly
2. https://github.com/voiceflow/general-runtime/blob/a8da9c94b2fcb72687d6ad8fe318c56c43c762e8/runtime/lib/Runtime/index.ts#L148 we've conflated `null` with a launch request. Sending `null` means it is always already handled.
The …

feat: new action system (VF-000)

---

lib/services/runtime/utils.ts
tests/lib/services/runtime/utils.unit.ts

**Fixes or implements VF-2478**
replace our (not good) Slate -> plain formatter with the Slate recommended method for serializing to plain text

fix: improve formatting of `trace.payload.message` (VF-2478)

---

lib/services/dialog/synonym.ts

**Fixes or implements VF-2479**
somewhere we're allowing invalid data to pass our validation. our code is written to work with strings but it's being given a number. in the interest of not spending 9999 hours tracking down specifically why the validator is not doing its job right i'm just guessing that making this one function more resilient will fix the issue in #235.
Fixes #235

fix: make `sanitize` function safer (VF-2479)

---

runtime/lib/Runtime/Stack/Frame/index.ts
runtime/lib/Runtime/cycleStack.ts
runtime/lib/Runtime/index.ts
tests/runtime/lib/Runtime/Stack/Frame/index.unit.ts

wanted to change the nomenclature to better describe what's going on.
So in the actual state, we obviously don't save the ENTIRE program/diagram into the stack.
https://stackoverflow.com/questions/6991135/what-does-it-mean-to-hydrate-an-object
When a request comes in, we only fetch the program for the top frame in the stack. This way we don't have to make it redundant. The actual stack frame in the state when saved to the DB is just a reference to the program.
So a better word is instead of "initializing" a frame when we do this, we are actually "hydrating" it with all the program data.
I've added a non-optimal function to hydrate the entire stack, its used only in very niche cases. …

feat: hydrate nomenclature (VF-000)

---

backend/api/routers/interact.ts
backend/api/routers/state.ts
lib/middlewares/project.ts
lib/services/interact.ts
runtime/lib/DataAPI/creatorDataAPI.ts
tests/server/state.unit.ts

**Fixes or implements VF-2429**
Adds support for the new API key format. New routes to interact with the API without providing a `versionID`. This is supported by using the API key to look up the latest version.

feat: dialog manager api key support (VF-2429)

---

backend/docs/openapi.yaml
lib/controllers/interact.ts
lib/services/interact.ts
lib/services/stateManagement.ts

**Fixes or implements VF-2492**
The `request` key has been a source of confusion, this renames in to `action` in a first step to hopefully clarifying how to use this API.

feat: rename request to action (VF-2492)

---

backend/docs/openapi.yaml

**Part of VF-1871**
When validating our OpenAPI spec with the openapi-generator tool, we get the following errors:
```
- attribute components.schemas.TextRequest.requuired is unexpected
- attribute components.securitySchemes.SecurityScheme name API Key doesn't adhere to regular
expression ^[a-zA-Z0-9\.-_]+$
- attribute
paths.'/state/{versionID}/user/{userID}/interact'(post).parameters.[verbose].default is
unexpected
```
This fixes those errors.
- `attribute components.schemas.TextRequest.requuired is unexpected`: Typo
- `attribute components.securitySchemes.SecurityScheme name API Key doesn't adhere to regular expression ^[a-zA-Z0-9\.-_]+$`: No spaces allowed according to the spec
- `attribute  paths.'/state/{versionID}/user/{userID}/interact'(post).parameters.[verbose].default is …

docs(openapi): fix three validation errors found in our OpenAPI spec (VF-1871) 

---

backend/docs/openapi.yaml

**Fixes or implements VF-1871**
fixes an incomplete refactoring from #244
our security scheme was renamed from `API Key` to `APIKey`, but the references weren't updated which causes validation errors

docs(openapi): fix security scheme name (VF-1871)

---

runtime/lib/Runtime/index.ts

Do not add base programs if they don't exist (all projects before a certain time don't have them). Pretty much that simple.
This is what was resulting in these errors:
They are programs not found

fix: check base program exists (VF-000)

---

runtime/lib/Handlers/code/index.ts
runtime/lib/Handlers/code/utils.ts
tests/runtime/lib/Handlers/code/index.unit.ts

**Fixes or implements VF-2654**
so when a variable is undefined on Voiceflow, and we want to change it on the code step,
in the http request we sent all undefined values are just dropped altogether when being sent to the code step. So when we try to actually modify it in the code-block microservice it is unreferenced and doesn't get sent back.
This was actually uncovered by connor's work on the API block, because now the API block is local and actually maps undefined to keys, but it is not the API block's fault, it is fine to set something to undefined.
This is because we need the something to be referenced as a key in order for it to be sent back:
https://github.com/voiceflow/general-runtime/blob/ee432fed620cb9be76fa4fa7aa426351c11fa24f/runtime/lib/Handlers/code/utils.ts#L94-L100
| …

fix: undefined code step keys (VF-2654)

---

lib/services/dialog/index.ts
tests/lib/services/dialog/index.unit.ts

After extensive testing with our dialog service (this should be renamed to entity filling), I decided to make some changes that better reflect the user's intentions.
We make too much use of the fallback intent. It should be up to the NLP to resolve something as a "None Intent", otherwise whatever else it resolves to is still valid data that can be made use of.
I've simplified the cases for entity filling. Suppose we are trying to fill out a pizza type for "pizza intent" with `size` & `type` entities: 
```
-> "what type of pizza do you want?" (Sys)
<- "help" (User)
```
* We will first send just "help" to LUIS to match, which will easily result in the "help intent". (incoming intent)
* Next, we send `${dm_prefix_hash} help`, which will more often than not, …

feat: entity filling incoming intent (VF-000)

---

package.json
yarn.lock

**Fixes or implements VF-2627**
Update `slate` to version `0.72` to remove a [security vulnerability with `immer`](https://github.com/voiceflow/general-runtime/security/dependabot/yarn.lock/immer/open)

chore(deps): update slate (VF-2627)

---

config.ts
documentation/env.md
lib/services/runtime/handlers/index.ts
runtime/lib/Handlers/api/index.ts
runtime/lib/Handlers/api/utils.ts
tests/runtime/lib/Handlers/api.unit.ts
types.ts

I saw this error after bumping the general-runtime package for alexa:
```
Error: env var: GENERAL_SERVICE_ENDPOINT not found
```
the alexa-runtime definitely doesn't need the `GENERAL_SERVICE_ENDPOINT` to work. Because we referenced `@/config` directly, the downstream runtimes now need the same environment variables.
Stems from: https://github.com/voiceflow/general-runtime/pull/255
Instead, they should be instantiated as the handlers get being added.
This is blocking some critical bug fixes for alexa.
`API_HANDLER_ENDPOINT` is no longer needed, this was a reference to the API microservice. It is done locally now.
| other_pr_master     | …

fix: api injection (VF-000)

---

lib/services/runtime/handlers/_v1.ts
tests/lib/services/runtime/handlers/_v1.unit.ts

**Fixes or implements VF-2727**
Although it is possible to infer the value of a variable from the variable state, it's a lot easier to consume for anyone using the API if it gets done directly on the runtime.
Uses the same `replaceVariables` used throughout the runtime for other fields.
So given a step like this
It will now produce this trace:

fix: expand custom variables (VF-2727)

---

runtime/lib/Handlers/api/utils.ts

**Fixes or implements VF-2713**
do not throw an error when the status code from a request in the API block is a 4xx or 5xx 
it's like a 1liner config option
also, get rid of the useless trycatch block

fix: handle HTTP 4xx & 5xx errors in API block (VF-2713)

---

lib/services/runtime/handlers/interaction.ts
lib/services/runtime/types.ts
runtime/lib/Constants/flags.ts
runtime/lib/Runtime/cycleHandler.ts
tests/lib/services/runtime/handlers/interaction.unit.ts
tests/runtime/lib/Runtime/cycleHandler.unit.ts

**Fixes or implements VF-2489**
This fixes an infinite loop when a choice entity is the same as the intent it is going to.
We store the last visited node on every runtime loop. This enables us to check that we aren't trying to handle the interaction that we just triggered a GOTO from.

fix: store the last visited node, check on interact (VF-2489)

---

backend/api/routers/api.ts
lib/services/runtime/handlers/api.ts
lib/services/runtime/handlers/index.ts
lib/utils.ts
runtime/lib/Handlers/api/index.ts
runtime/lib/Handlers/api/types.ts
runtime/lib/Handlers/api/utils.ts
runtime/lib/Handlers/index.ts

**Fixes or implements PL-120**
The `createResponseConfig` was not a generic utility, so should not have lived where it was.
By removing the defaults from the exported library package portion, it would mean each runtime that is dependant on this library portion would also have to add defaults themselves. I've attempted to retain these defaults.
- https://github.com/voiceflow/XXXXXXXXX/pull/123

refactor: pass config in directly (PL-120)

---

lib/services/runtime/handlers/cardV2.ts

**Fixes or implements CT-1050**
For card steps we aren't doing variable substitutions in the buttons - this means that the URL action with variables in it is broken, enough though the FE makes it look like its supported:

fix: buttons substitution [bugfix] (CT-1050)

---

lib/services/runtime/handlers/captureV2/captureV2.ts

we've started special compile patterns for alexa nodes on general-service:
https://github.com/voiceflow/general-service/blob/0ef2b16987e80332f15a43872d0cde534058daff/lib/clients/platform/handlers/captureV2/compiler.alexa.ts#L28-L70
In particular when we are trying to get the entire user response we do this:
```
if (isQueryCapture(capture)) {
node.intent = {
name: QUERY_INTENT_NAME,
entities: [QUERY_SLOT_NAME],
};
node.variable = capture.variable || undefined;
}
```
because Alexa needs a special slot type and intent to do it. This confuses the prototype tool in thinking that it is no longer a "Entire user reply" query.
What I've updated is that the runtime will also write the query to variable if it is set.

fix: alexa capture step prototype (BUG-294)

---

lib/services/runtime/types.ts
lib/services/state/index.ts
runtime/lib/Runtime/index.ts

one major issue we have right now is that existing sessions will never receive new upgrades.
Imagine a project like this, where there is no exit condition:
This means that the user's session's stack will ALWAYS be on that version, because it always references the `programID` from that particular version.
What I've done is take advantage of the fact that we have a base trace frame (bottom of the stack) that is the versionID. What we do now is check if the base frame is in sync with whatever version "production" is, if not we reset the session.
This might be a little jarring because it could mean that the user's session resets in the middle of a conversation - but this is better than people getting really frustrated when they test the DMAPI because they never see their new version.

feat: reset session stack production [bugfix] (PL-000)

---

backend/api/routers/test.ts
lib/controllers/test.ts
lib/services/billing.ts
lib/services/runtime/handlers/aiResponse.ts
lib/services/runtime/handlers/aiSet.ts
lib/services/runtime/handlers/noMatch.ts

Right now if you hit a token limit the runtime will just fail silently, the `VError` gets swallowed up by the handler:https://github.com/voiceflow/general-runtime/blob/39ceeb3629fe2867f10940793c4f922a51a82f83/runtime/lib/Runtime/cycleHandler.ts#L33-L45
Also the frontend has no way to visualize this error at the moment, so for the short term, I think it is better to just explicitly surface it as a text or something.
Right now I'm getting a large influx of "bug" reports from users reporting their LLM features aren't working.

fix: token limit error message [bugfix] (LLM-000)

---

lib/services/runtime/handlers/_v1.ts

Old custom action nodes on the program look like this:
```
{
"id": "65417846329b6455cb69f2a9",
"_v": 1,
"type": "name",
"stop": false,
"payload": "body",
"paths": [
{ "event": { "type": "path 1" }, "nextID": null },
{ "event": { "type": "path 2" }, "nextID": null }
],
"defaultPath": 0
}
```
Basically new custom action nodes on the program look like this:
```
{
"id": "65417694125e184893a0b2e3",
"_v": 1,
"type": "trace",
"stop": true,
"payload": {
"name": "name",
"body": "body",
"bodyType": "json"
},
"paths": [
{ "event": { "type": "path 1" },  "nextID": null },
{ "event": { "type": "path 2" }, "nextID": null }
],
"defaultPath": 0
}
```
We're moving everything inside `payload`. There's one additional piece of data: `bodyType`.
If `type === 'trace'` we will look at `bodyType`, if it is …

fix: custom action json parse (CT-000)

---

lib/services/runtime/index.ts
lib/services/state/index.ts

I apologize for this piece of somewhat convoluted logic. We need to set the request to the builtin `last_event`, so we don't want to set it to `null` at the `state` stage of the pipeline.
The center of the issue is here:
https://github.com/voiceflow/general-runtime/blob/78a10d27ad3d0d2e34f7e939779d35ec242c2bba/runtime/lib/Runtime/index.ts#L224-L229
Only the actual runtime cares about this, so we are setting it right before it gets fed into the runtime, all the other logic is the same. I know the mutation is kind icky, the `context` is a newly generated object for this call so it doesn't matter too much:
https://github.com/voiceflow/general-runtime/blob/5be4e4be8b706b60194c9242e516c3b691074f6f/lib/services/runtime/index.ts#L49
There is another alternative to this: …

fix: move launch request remapping downstream (CT-000)

---

backend/api/routers/nlu.ts
lib/middlewares/index.ts
lib/middlewares/inferenceLimit.ts

This is not the best implementation, but today `general-runtime` was crashed by a client testing inference.
His version was a large document (1.1MB) and that would cause the `general-runtime` MongoDB connection to completely crash. This is because we were fetching the entire document for every inference call. 
I had to make an emergency patch https://github.com/voiceflow/general-runtime/commit/6d40e2589948a7e921cff8ebd882e70aaaed189f 
this more aggressive rate-limit should also prevent it from short circuiting. 
This is not the prettiest implementation but it is the same pattern as the llm rate limit. We'll need to do a larger rate limit refactor for general runtime in the near future.

fix: add inference rate limit (PL-000)

---

lib/services/runtime/index.ts

It seems that `payload` can be undefined, which the types do not indicate.

fix: check button label before setting last utterance (PL-000) [bug-fix]

---

lib/services/aiAssist.ts
lib/services/runtime/handlers/utils/ai.ts

- https://github.com/voiceflow/XXXXXXXXX/pull/123
- New required environment variables
- Renaming of interfaces (API routes, request/response interface, etc)
- Bug fixes are accompanied by an updated or new test
- New features are accompanied by a new test

feat: add builtin vf-memory variable (CT-000)

---

lib/services/runtime/index.ts
lib/services/runtime/types.ts

Caused by: https://github.com/voiceflow/general-runtime/pull/698
The `isPathRequest` guard did not assert a payload label existed, so when using that in the ai memory variable the types indicate that payload will be there.
So accessing `payload.label` resulted in a "Cannot read payload from undefined" error.
This change adds a `payload.label` check to guard itself, as the typing for `payload` is wrong, and could be null or undefined.
See: https://github.com/voiceflow/general-runtime/pull/690

fix: payload type is wrong, can be undefined (PL-752) [bugfix]

---

.circleci/continue_config.yml.tmpl

**Fixes or implements DX-1579**
Remove the override to use `ci` branch for smoke tests, it will now track `master`
- New required environment variables
- Renaming of interfaces (API routes, request/response interface, etc)
- Bug fixes are accompanied by an updated or new test
- New features are accompanied by a new test

ci: use master branch for smoke tests (DX-1579)

---

lib/services/classification/interfaces/nlu.interface.ts
lib/services/classification/predictor.class.ts
lib/services/dialog/index.ts

We were fully missing the logic for dialog service from the old flow, a bit of an oversight.
this was causing issues during my tests with entity filling, and it was unable to get the entities.
In the old code, this is where it was being passed through:
https://github.com/voiceflow/general-runtime/blob/ca5c4833113610dbca3fce240c933f92bb6d8050/lib/services/dialog/index.ts#L154

fix: dm request logic (PL-844)

---

lib/clients/dataAPI.ts
lib/clients/prototypeDataAPI.ts
lib/controllers/nlu.ts
lib/services/classification/classification.const.ts
lib/services/classification/classification.utils.ts
lib/services/classification/predictor.class.ts
lib/services/dialog/index.ts
lib/services/nlu/index.ts

the `version.settings` is strictly optional.
https://github.com/voiceflow/creator-app/blob/cfc893c267d5a9562973fceb01b3f8821668c504/libs/dtos/src/version/version.dto.ts#L33
All existing projects don't have it. 
And the migrations only target projects with existing projects.
The very first test I ran basically failed, so a bit of an oversight there.
I intend to just merge this into [tyler/test-classification-endpoint/PL-844](https://github.com/voiceflow/general-runtime/tree/tyler/test-classification-endpoint/PL-844)

fix: fix settings (PL-844)

---

lib/services/classification/predictor.class.ts
lib/services/nlu/index.ts

**Fixes or implements PL-844**
Debug tracing is best left within the `Predictor` class as it has all the context and ordering of events.
`Predictor extends EventEmitter` and emits debug information. The caller can choose to listen and map to traces, or ignore all together

refactor: predictor as event emitter for debug tracing (PL-844)

---

lib/controllers/test/index.ts

If NLU isn't used, use the NLC result as the NLU result.

feat: use nlc in place of nlu for test result (PL-844)

---

lib/controllers/test/index.ts

Use the returned prediction that would contain the fallback in the preview/test endpoint

fix: use prediction to get fallback in preview (PL-926)

---

runtime/lib/Handlers/api/api.interface.ts
runtime/lib/Handlers/api/index.ts
runtime/lib/Handlers/api/utils.ts
tests/runtime/lib/Handlers/api.unit.ts

update the interface to not be dependent on the `node-fetch` `Response` object and we can use something that can be sent over HTTP/stringified.

fix: add api response interface (PL-927)

---

.circleci/continue_config.yml.tmpl

* Linear [ticket](https://linear.app/voiceflow/issue/IN-1271/add-events-to-e2e-logs) 
* Include kubernetes events in the e2e gathered logs 
* https://github.com/voiceflow/orb-common/pull/264
* https://github.com/voiceflow/infrastructure/pull/704

feat: add kubernetes events to logs (IN-1271)

---

lib/clients/unleash/index.ts

If no env vars are set:
https://github.com/voiceflow/general-runtime/blob/5aa2cef79f5c519014b376f29d17f048655e9d6b/lib/clients/unleash/index.ts#L54-L58
instance never gets initialized, so we should not throw an error.

fix: allow production instances no unleash config (ENG-208)

---

.circleci/continue_config.yml.tmpl
Dockerfile

- Build multi-platform images for linux/amd64, linux/arm64
- integration tests through orb but pulling node_modules from amd64 docker build for use by executor
`update_track` should probably run after `test` job, otherwise we're duping the build really

build(arm): build for ARM at every stage (PL-000)

---

.circleci/continue_config.yml.tmpl

We were only checking the unit test results for test failures but not compilation failures in the test files.
- Add a check for "Error: Cannot find module" or "Require stack:" in the logs
- store test logs files as artifacts

fix(build): catch and fail on unit test compilation errors (IN-1386)
