voiceflow/general-runtime

- lib/services/prototype/handlers/interaction.ts
made to match `alexa-runtime`
https://github.com/voiceflow/alexa-runtime/pull/104
> fix: choice block

- backend/api/index.ts
- lib/clients/index.ts
- lib/clients/prototypeServerDataApi.ts
- lib/services/prototype/handlers/command.ts
- lib/services/prototype/handlers/interaction.ts
- lib/services/prototype/utils.ts
- package.json
- tests/lib/services/prototype/index.unit.ts
- tests/server/prototype.unit.ts
- yarn.lock
**Depends on:** https://github.com/voiceflow/runtime/pull/69
> feat: use prototype programs

- lib/clients/index.ts
- lib/controllers/interact.ts
- lib/services/chips/index.ts
- lib/services/dialog/index.ts
- lib/services/nlu/index.ts
- lib/services/runtime/index.ts
- lib/services/state/cacheDataAPI.ts
- lib/services/state/index.ts
- package.json
- tests/lib/services/dialog/fixture.ts
- tests/lib/services/dialog/index.unit.ts
- tests/lib/services/nlu/index.unit.ts
- tests/lib/services/runtime/index.unit.ts
- tests/lib/services/state/index.unit.ts
- types.ts
- yarn.lock
attach a special dataAPI that caches versions/projects to the context for use through all the handlers
> feat: cached data

- lib/services/dialog/index.ts
- lib/services/dialog/utils.ts
- package.json
- yarn.lock
> fix: allow dm prompts

- .env.test
- config.ts
- lib/clients/dataAPI.ts
- lib/clients/index.ts
- package.json
- tests/lib/clients/dataAPI.unit.ts
- types.ts
- yarn.lock
tested end to end - works well
> feat: creator-api

- lib/services/nlu/index.ts
- lib/services/nlu/nlc.ts
- package.json
- yarn.lock
pretty simple.
First check NLC strictly (no value general slots) and if the query matches word for word, then resolve the intent.
Then try NLP/NLU Luis
Finally if that fails do a broad NLC check with open slots
This will make the prototype much smarter, because even if you have new untrained additions, it will still kind of work
> feat: nlc strict check

- netlify.toml
- typedoc.js
**Fixes or implements CORE-4898 **
trying to create a path on netlify + subdomain
> chore: custom domain for documentation (CORE-4898)

- lib/services/dialog/utils.ts
**Fixes or implements CORE-4959**
> fix: shorten hash value (CORE-4959)

- .circleci/config.yml
- netlify.toml
**Fixes or implements CORE-4898**
force generation of the documentation and test new orb
> perf: force generation of documentation and new orb (CORE-4898)

- .circleci/config.yml
**Fixes or implements CORE-4901**
> feat: fix slack channel post (CORE-4901)

- .circleci/config.yml
**Fixes or implements CORE-4901**
> fix: fix slack notification (CORE-4901)

- .env.test
- README.md
- config.ts
- documentation/env.md
- lib/services/runtime/handlers/index.ts
- package.json
- types.ts
- yarn.lock
**Fixes or implements CORE-5059**
Specialized API Handler - going to leave undefined by default in docs now
> feat: local api(CORE-5059)

- config.ts
- package.json
- types.ts
- yarn.lock
[runtime](https://github.com/voiceflow/runtime/pull/94)
> feat: local code handler (CORE-5076)

- lib/services/runtime/handlers/index.ts
- lib/services/runtime/handlers/visual.ts
- logger.ts
- package.json
- tests/lib/services/runtime/handlers/visual.unit.ts
- yarn.lock
**Fixes or implements CORE-XXX**
> feat: add visual handler (CORE-4884)

- lib/services/nlu/index.ts
- lib/services/runtime/handlers/capture.ts
- lib/services/runtime/handlers/interaction.ts
- lib/services/runtime/index.ts
- lib/services/runtime/utils.ts
- tests/lib/services/runtime/handlers/capture.unit.ts
- tests/lib/services/runtime/handlers/interaction.unit.ts
- tests/lib/services/runtime/index.unit.ts
**Fixes or implements CORE-5004**
https://github.com/voiceflow/general-service/pull/55
https://github.com/voiceflow/creator-app/pull/2923
> feat: add intent confidence to debug message (CORE-5004)

- package.json
- yarn.lock
Update api-sdk and runtime versions
> fix: update api-sdk and runtime versions (CORE-000)

- config.ts
- lib/clients/rateLimiter.ts
- lib/clients/redis.ts
- types.ts
for anyone running general-runtime as a standalone - they do not need a redis instance, rate limiting can be done through memory
> fix: optional redis (CORE-000)

- README.md
**Fixes or implements CORE-5294**
Documentation on the Interact Endpoint for users who want to hit the endpoint directly.
View the file here: https://github.com/voiceflow/general-runtime/blob/6b3678e7cea8cd049659a0d6b56a0fe2af8cb778/README.md
- [ ✅  ] title of PR reflects the branch name
- [ ✅  ] all commits adhere to conventional commits
> docs: Interact Endpoint Documentation (CORE-5294)

- package.json
- yarn.lock
**Fixes or implements CORE-5385**
Upgrading the dependencies
`yarn upgrade @voiceflow/api-sdk@1.28.0 @voiceflow/general-types@1.36.0 @voiceflow/runtime@1.25.0`
None
| `alexa-runtime` | [link](https://github.com/voiceflow/alexa-runtime/pull/141) |
| `google-runtime`     | [link](https://github.com/voiceflow/google-runtime/pull/87) |
| `general-runtime`     | [link](https://github.com/voiceflow/general-runtime/pull/84) |
| `general-service`     | [link](https://github.com/voiceflow/general-service/pull/72) |
| `luis-authoring-service` | [link](https://github.com/voiceflow/luis-authoring-service/pull/48) |
| `database-cli` | [link](https://github.com/voiceflow/database-cli/pull/55) |
- ~~[ ] appropriate tests have …
> feat: upgrading dependencies for prototype share view (CORE-5385)

- package.json
- yarn.lock
**Fixes or implements CORE-5385**
Updating dependencies to fix desync issue.
`yarn upgrade @voiceflow/api-sdk@1.28.0 @voiceflow/general-types@1.36.0 @voiceflow/runtime@1.26.0`
None
None
See ticket
> feat: updating depends to fix deps desync issue (CORE-5385)

- lib/services/runtime/handlers/index.ts
- lib/services/runtime/handlers/state/index.ts
- lib/services/runtime/handlers/state/preliminary.ts
- tests/lib/services/runtime/handlers/state/preliminary.unit.ts
https://creator-env-hopeful-morse.development.voiceflow.com/
> feat: preliminary handler (CORE-4993)

- lib/services/runtime/handlers/_v1.ts
- lib/services/runtime/handlers/event/index.ts
- lib/services/runtime/handlers/state/preliminary.ts
- lib/services/runtime/types.ts
- package.json
- tests/lib/services/runtime/handlers/_v1.unit.ts
- tests/lib/services/runtime/handlers/event/index.unit.ts
- tests/lib/services/runtime/types.unit.ts
- yarn.lock
to-do:
- update general-types
[general-types](https://github.com/voiceflow/general-types/pull/59)
[runtime-client-js](https://github.com/voiceflow/runtime-client-js/pull/52)
> feat: custom stop on v1 (CORE-5457)

- lib/clients/metrics.ts
- lib/controllers/interact.ts
log whenever someone passes an API key in (so not prototype tool)
> fix: log sdk requests (CORE-000)

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- backend/docs/index.html
- backend/docs/openapi.yaml
- backend/openapi.yaml
> feat: open api docs

- lib/services/dialog/index.ts
- lib/services/dialog/utils.ts
- tests/lib/services/dialog/fixture.ts
- tests/lib/services/dialog/index.unit.ts
**Fixes or implements VF-113**
add default voice to the DM
> fix: tts in the dm (VF-113)

- yarn.lock
> chore: upgrading git-branch-check

- .nycrc.json
- lib/services/chips/index.ts
- lib/services/nlu/nlc.ts
- lib/services/runtime/handlers/command.ts
- lib/services/runtime/handlers/interaction.ts
- lib/services/runtime/handlers/noMatch.ts
- lib/services/runtime/handlers/repeat.ts
- lib/services/runtime/utils.ts
- tests/lib/services/chips/index.unit.ts
- tests/lib/services/chips/utils.unit.ts
- tests/lib/services/nlu/nlc.unit.ts
- tests/lib/services/runtime/handlers/capture.unit.ts
- tests/lib/services/runtime/handlers/command.unit.ts
- tests/lib/services/runtime/handlers/event/index.unit.ts
- tests/lib/services/runtime/handlers/interaction.unit.ts
- tests/lib/services/runtime/handlers/noMath.unit.ts
- tests/lib/services/runtime/handlers/repeat.unit.ts
- tests/lib/services/runtime/handlers/speak.unit.ts
- tests/lib/services/runtime/handlers/state/stream.unit.ts
- tests/lib/services/runtime/handlers/stream.unit.ts
- tests/lib/services/runtime/init.unit.ts
- tests/lib/services/runtime/utils.unit.ts
aimed for at least yellow on all files in this PR (will be adding more later)
> test: suite (VF-253)

- .env.test
> feat: updating port numbers (VF-000)

- package.json
- yarn.lock
**Fixes or implements VF-185**
* update `@voiceflow/*` dependencies to include new expression types
> feat: update @voiceflow/* dependencies (VF-185)

- tsconfig.build.json
> fix: remove build exclude (VF-000)

- .circleci/config.yml
> feat: add warden to prod

- lib/services/runtime/handlers/_v1.ts
- lib/services/runtime/handlers/event/index.ts
- lib/services/runtime/types.ts
- lib/services/runtime/utils.ts
- package.json
- runtime/lib/Context/types.ts
- runtime/lib/Lifecycle/types.ts
- runtime/lib/Runtime/Trace/index.ts
- yarn.lock
> fix: update types (VF-000)

- lib/services/runtime/handlers/capture.ts
- lib/services/runtime/handlers/command.ts
- lib/services/runtime/handlers/interaction.ts
- lib/services/runtime/handlers/noMatch.ts
- tests/lib/services/runtime/handlers/capture.unit.ts
- tests/lib/services/runtime/handlers/command.unit.ts
- tests/lib/services/runtime/handlers/interaction.unit.ts
- tests/lib/services/runtime/handlers/noMath.unit.ts
- yarn.lock
I had to not reference general-types because the latest version is broken until
https://github.com/voiceflow/general-runtime/pull/130 gets merged
> fix: path traces (VF-000)

- runtime/lib/Handlers/code/index.ts
- runtime/lib/Handlers/code/utils.ts
- runtime/lib/Runtime/Store/index.ts
- tests/runtime/lib/Handlers/ifV2.unit.ts
**Fixes or implements VF-1170**
Get the variables from `vm2` via official API and add prototypes to the incoming variables. Better formating for the changed vars.
> fix: code handler (VF-1170)

- package.json
- runtime/lib/Runtime/Store/index.ts
In this original PR by @z4o4z https://github.com/voiceflow/general-runtime/pull/140 we introduced a formatting system that basically goes through an object and recreates it, ensuring the prototype properties were attached to everything. 
However this leads to a big problem because downstream repos like `alexa-runtime` rely on putting very complicated class instances into the `turn` store and they contain circular dependencies, crashing alexa-runtime. I see `Maximum call stack size exceeded` a lot.
So my proposed solution for now is to use this only for the code block. But I also want to have a more robust system in the future as well to stop circular dependencies, still preserve the object, but still assign prototypes to all objects somehow. Reference how …
> fix: remove payload formatting for stores (VF-000)

- backend/docs/openapi.yaml
Fix typo in the Node.js example.
> docs: fix Node.js example (VF-000)

- lib/services/runtime/index.ts
- lib/services/state/index.ts
- tests/lib/clients/analytics.unit.ts
- tests/lib/services/runtime/index.unit.ts
- tests/lib/services/state/index.unit.ts
we can get rid of these if they never say anything and the ingest is pretty stable. 
> fix: safely handle ingest errors (VF-000)

- lib/services/runtime/utils.ts
**Fixes or implements VF-1226**
We're creating and returning empty choice steps for the frontend. Probably the problem is in the general-service, I'll keep debugging it, but for now (just to stop the blood) I'm filtering the choice buttons without name (empty ones) in the runtime so we don't have this problem anymore on the frontend.
> fix: filters buttons with empty name (VF-1226)

- config.ts
- lib/clients/analytics.ts
- package.json
- tests/lib/clients/analytics.unit.ts
- yarn.lock
> fix: some bug fiexes for e2e and anlytics (VF-000)

- .circleci/config.yml
> ci: added e2e check

- runtime/lib/Handlers/integrations/utils.ts
**Fixes or implements VF-1169**
As we dont use mathjs we need to parse nums manually
TO-DO: update `general-runtime` package in google and alexa runtimes
> fix: google sheets val to num (VF-1169)

- lib/clients/analytics.ts
> fix: timestamp (VF-000)

- backend/constants.ts
- backend/expressMiddleware.ts
- config.ts
- lib/services/runtime/index.ts
- types.ts
**Fixes or implements VF-1399**
- Minor performance improvements
- Adds a `ERROR_RESPONSE_MS` environment variable (default: `10000`)
This allows you to have API blocks that take a while to run
> feat: better support for big JSON (VF-1399)

- backend/expressMiddleware.ts
- lib/clients/analytics.ts
- lib/services/dialog/index.ts
- lib/services/nlu/nlc.ts
- lib/services/runtime/handlers/text.ts
- lib/services/runtime/index.ts
- lib/services/state/index.ts
- lib/services/tts/index.ts
- lib/utils.ts
- package.json
- server.ts
- start.ts
- yarn.lock
**Fixes or implements VF-1476**
Cleanup logging.
- https://github.com/voiceflow/general-runtime/pull/165
- https://github.com/voiceflow/alexa-runtime/pull/190
- https://github.com/voiceflow/google-runtime/pull/131
- voiceflow/logger#26
> fix: cleanup logs (VF-1476)

- renovate.json
**Fixes or implements VF-1187**
Adds [our team's Renovate config](https://github.com/voiceflow/renovate-config#readme) to this repo.
Once the Renovate GitHub app is granted access to this repo it should begin spitting out dependency update PRs.
This is the first real repo we'll be testing on so we may tweak the config before rolling it out to other repos/teams.
> chore: enable Renovate (VF-1187)

- app.config.js
- ingest.ts
- lib/clients/analytics.ts
- package.json
- server.ts
- tests/lib/clients/ingest-client.unit.ts
- Add export map for nicer imports (in supported Node.js + TypeScript apps, which is none of ours atm)
- Only publish necessary files
> fix: fix package exports (VF-000)

- app.config.js
- ingest.ts
- lib/clients/analytics.ts
- package.json
- server.ts
- tests/lib/clients/ingest-client.unit.ts
Reverts voiceflow/general-runtime#190
> fix: fix docker build (VF-000)

- .circleci/config.yml
This fixes the e2e failures by updating to the latest version of voiceflow/commmon orb.
> fix(deps): bump orb version (VF-000)

- runtime/lib/Runtime/Stack/index.ts
- runtime/lib/Runtime/cycleStack.ts
- runtime/lib/Runtime/index.ts
- tests/runtime/lib/Runtime/cycleStack.unit.ts
- tests/runtime/lib/Runtime/index.unit.ts
check if the versionID program exists or not, use rootDiagramID if not.
> feat: base program version id (VF-000)

- lib/services/runtime/init.ts
- runtime/lib/Runtime/cycleStack.ts
- runtime/lib/Runtime/index.ts
- tests/lib/services/runtime/init.unit.ts
- tests/runtime/lib/Runtime/cycleStack.unit.ts
> fix: fix base flow logic (VF-000)

- .circleci/config.yml
- Dockerfile
- Dockerfile.e2e
- package.json
- runtime/lib/Handlers/code/index.ts
- runtime/lib/Handlers/code/utils.ts
- runtime/lib/Handlers/ifV2.ts
- runtime/lib/Handlers/index.ts
- runtime/lib/Handlers/setV2.ts
- tests/runtime/lib/Handlers/code/index.unit.ts
- tests/runtime/lib/Handlers/code/utils.unit.ts
- tests/runtime/lib/Handlers/setV2.unit.ts
- yarn.lock
**Fixes or implements VF-2375**
Add the use of isolated-vm to be used to run code (provided from code block or IFV2 expressions) if requireFromUrl is not used inside the code.
Isolated-vm requires extra installation steps, mentioned here:
https://github.com/laverdet/isolated-vm#:~:text=Alternatives-,REQUIREMENTS,-This%20project%20requires
So will need to coordinate with infra to add.
> feat: add new local user code runner (VF-2375)

- README.md
**Fixes or implements VF-2375**
Add isolated-vm installation instructions to README
> chore: readme (VF-2375)

- backend/docs/openapi.yaml
> docs: dialog manager api key docs (VF-2429)

- backend/docs/openapi.yaml
> docs: reflect renamed action prop (VF-2492)

- lib/middlewares/project.ts
**Fixes or implements VF-2494**
It can be confusing when you get a random 500 error when providing a workspace api key. We cannot infer the project and version using a workspace api key since it is not attached to a project, therefore requests using it must provide the versionID.
Adds a better error if a project is not found.
> feat: add error when project version cannot be found using given api key (VF-2494)

- .circleci/config.yml
- .env.e2e
- .env.test
- config.ts
- lib/clients/index.ts
- lib/clients/metrics.ts
- lib/services/dialog/utils.ts
- lib/services/runtime/handlers/capture.ts
- package.json
- tests/lib/clients/metrics.unit.ts
- tests/server/fixture.ts
- tests/server/interact.unit.ts
- types.ts
- yarn.lock
**Fixes or implements VF-1458**
replace datadog with prometheus compatible metrics
- https://github.com/voiceflow/alexa-runtime/pull/224
- https://github.com/voiceflow/google-runtime/pull/174
> feat: implement new metrics (VF-1458) 

- lib/services/dialog/index.ts
- lib/services/dialog/utils.ts
- lib/services/runtime/handlers/captureV2.ts
- lib/services/runtime/handlers/index.ts
- lib/services/runtime/handlers/noMatch.ts
- lib/services/runtime/handlers/state/preliminary.ts
- lib/services/runtime/handlers/utils/entity.ts
- lib/services/runtime/types.ts
- tests/lib/services/dialog/index.unit.ts
- tests/lib/services/runtime/handlers/captureV2.unit.ts
**Fixes or implements VF-2391**
New capture block! We can just reuse the existing one for now for convenience.
> feat: capture V2 implementation (VF-2391)

- lib/services/runtime/handlers/noReply.ts
- tests/lib/services/runtime/handlers/noReply.unit.ts
**Fixes or implements VF-2512**
> feat: no reply buttons (VF-2512)

- backend/docs/openapi.yaml
improves our spec's compatibility
> docs: stop using null as a type in OpenAPI spec (VF-000)

- lib/services/runtime/handlers/utils/entity.ts
**Fixes or implements VF-2788**
The first time the an entity is not filled in a capture, we would trigger a nomatch and the repropmt. This fixes so the first time we do a reprompt, then if we dont match again we trigger a nomatch.
If `NO_MATCHES_COUNTER` isn't set yet, we know we haven't trigger a no match yet. So we can initialize the counter and set elicit to false. When elicit is false it does not trigger the no match prompt in the dialog handler.
If we've initialized the counter, we set elicit to true, so the dialog handler adds the no match trace.
> fix: do not trigger no match on first entity fill miss (VF-2788)

- lib/services/runtime/handlers/interaction.ts
- runtime/lib/Constants/flags.ts
- runtime/lib/Runtime/cycleHandler.ts
- tests/lib/services/runtime/handlers/interaction.unit.ts
- tests/runtime/lib/Runtime/cycleHandler.unit.ts
Reverts voiceflow/general-runtime#276
> Revert "fix: store the last visited node, check on interact (VF-2489)"

- .eslintignore
- backend/api/routers/interact.ts
- backend/api/routers/state.ts
- config.ts
- lib/controllers/interact.ts
- lib/controllers/stateManagement/index.ts
- lib/middlewares/project.ts
- lib/services/dialog/index.ts
- lib/services/interact/index.ts
- lib/services/nlu/index.ts
- lib/services/slots/index.ts
- lib/services/stateManagement.ts
- tests/lib/middlewares/project.unit.ts
- tests/lib/services/dialog/fixture.ts
- tests/lib/services/dialog/index.unit.ts
- tests/lib/services/interact/interact.unit.ts
- tests/lib/services/nlu/index.unit.ts
- tests/lib/services/state/index.unit.ts
- tests/server/interact.unit.ts
- tests/server/state.unit.ts
- types.ts
**Fixes or implements VF-3490**
- https://github.com/voiceflow/XXXXXXXXX/pull/123
> fix: unlink version alias from prediction (VF-3490)

- .depcheckrc
- lib/clients/index.ts
- lib/middlewares/auth.ts
- package.json
- yarn.lock
remove all non-public internal packages.
We won't use the SDK but instead directly call the API via axios now.
> fix: remove internal package (PL-000)

- lib/services/runtime/handlers/utils/knowledgeBaseNoMatch/answer.ts
**Fixes or implements BUG-446**
Changed prompt to make it respond better
- New required environment variables
- Renaming of interfaces (API routes, request/response interface, etc)
- Bug fixes are accompanied by an updated or new test
- New features are accompanied by a new test
> fix: added Not Found to claude responses (BUG-446)

- lib/middlewares/llmLimit.ts
- lib/middlewares/rateLimit.ts
- lib/services/runtime/handlers/interaction/interaction.alexa.ts
- lib/services/runtime/handlers/interaction/interaction.ts
**Fixes or implements BUG-453**
On interaction calls the no reply prompt was not being sent to the adapter/alexa.
Very similar to what we did on the captureV2 handler, there is a tiny specific logic on the interaction handler to account for this.
> fix: add alexa no reply on interaction handler (BUG-453)

- .vscode/launch.json
- backend/api/routers/test.ts
- lib/controllers/test.ts
- lib/services/runtime/handlers/utils/knowledgeBase/index.ts
- lib/services/runtime/handlers/utils/knowledgeBase/question.ts
- Add back the missing `/knowledge-base-prompt` route.
- Check and consume tokens during knowledge base tests.
> feat: knowledge base prompt route, token quota (PL-000) [bugfix]

- lib/middlewares/billing.ts
- lib/services/billing.ts
- lib/services/index.ts
- lib/services/runtime/handlers/aiResponse.ts
- lib/services/runtime/handlers/aiSet.ts
- lib/services/runtime/handlers/noMatch.ts
- lib/services/runtime/handlers/utils/generativeNoMatch.ts
- lib/services/runtime/handlers/utils/knowledgeBase/index.ts
- tests/lib/services/runtime/handlers/noMatch.unit.ts
Check and consume the Open AI token quota in runtime handlers.
> feat: check and consume tokens in runtime (PL-000) [bugfix]

- lib/clients/ai/types.ts
- lib/services/runtime/handlers/aiResponse.ts
- lib/services/runtime/handlers/aiSet.ts
- lib/services/runtime/handlers/noMatch.ts
- lib/services/runtime/handlers/utils/generativeNoMatch.ts
- lib/services/runtime/index.ts
- lib/services/state/index.ts
- runtime/lib/Client/index.ts
- runtime/lib/Context/types.ts
- runtime/lib/Runtime/index.ts
- tests/lib/services/runtime/index.unit.ts
- tests/lib/services/state/index.unit.ts
- tests/runtime/lib/DataAPI/index.unit.ts
Get workspace plan from billing service, gate requests to LLMs using it.
Related: https://github.com/voiceflow/creator-api/pull/1256
> feat: grab workspace plan [bugfix] (PL-000)

- lib/clients/ai/anthropic/utils.ts
- lib/clients/ai/openai/gpt3.ts
- lib/clients/ai/openai/gpt3_5.ts
- lib/clients/ai/openai/gpt4.ts
Track total tokens used for OpenAI models, not just the completion.
Changes Claude usage to 0 from 1. Currently don't see a token usage returned from them.
> fix: track total token usage (PL-000)

- lib/clients/ai/anthropic/utils.ts
- lib/controllers/test.ts
- lib/services/runtime/handlers/aiResponse.ts
- lib/services/runtime/handlers/aiSet.ts
- lib/services/runtime/handlers/noMatch.ts
Floors the token calculation for claude so we aren't sending floats to billing.
Also catches errors around consumption as this is a side effect and shouldn't block the user.
> fix: floor token calculation for claude (BUG-490)

- lib/clients/ai/anthropic/claude_v1.ts
- lib/clients/ai/anthropic/utils.ts
- lib/clients/ai/openai/gpt3.ts
- lib/clients/ai/openai/gpt3_5.ts
- lib/clients/ai/openai/gpt4.ts
- lib/clients/ai/openai/utils.ts
- lib/clients/ai/types.ts
Apply a token multiplier to some LLM models
> feat: apply LLM token multipliers (BUG-489)

- lib/controllers/nlu.ts
- lib/services/dialog/index.ts
- lib/services/nlu/index.ts
- lib/services/nlu/utils.ts
too many requests consuming massive documents from Mongo, killing the mongo connection.
> fix: emergency nlp inference hotfix [bugfix] (CT-000)

- lib/services/nlu/index.ts
- tests/lib/services/nlu/index.unit.ts
hard code everything to not filter.
> fix: remove filter intents [bugfix] (CT-000)

- lib/services/nlu/llmHybrid.ts
- lib/services/state/index.ts
- package.json
- runtime/lib/Runtime/utils/variables.ts
- tests/lib/services/state/index.unit.ts
- yarn.lock
**Fixes or implements CV3-942**
Change the `general-runtime` so that we initialize the default values based on the CMS variable declarations. 
`general-service` will be changed so that compiled variable declaration information is stored in `version.prototype.surveyorContext.cmsVariables`. This includes the user-set default values for each variable.
At the `initializeVariables()` method of `general-runtime`, we add a new line called `initializeFromCMSVariables()` which will  create an overwrite patch to set each variable to its CMS default value.
N/A
N/A
- https://github.com/voiceflow/general-runtime/pull/694
- https://github.com/voiceflow/general-service/pull/558
- https://github.com/voiceflow/libs/pull/501
- https://github.com/voiceflow/creator-app/pull/7761
- New required environment …
> feat: initializing variables from cms (CV3-942)

- lib/services/runtime/handlers/utils/knowledgeBase/index.ts
- lib/services/runtime/handlers/utils/knowledgeBase/types.ts
* Enable KB on Keybank 
* https://github.com/voiceflow/general-runtime/pull/696
> feat: enable KB for Keybank (IN-1184)

- lib/services/runtime/handlers/utils/knowledgeBase/index.ts
- lib/services/runtime/handlers/utils/knowledgeBase/types.ts
* https://voiceflow.atlassian.net/browse/IN-1186
> feat: enable kb on usaa (IN-1186)

- lib/controllers/public/index.ts
- runtime/lib/DataAPI/localDataAPI.ts
- runtime/lib/DataAPI/mongoDataAPI.ts
- runtime/lib/DataAPI/types.ts
Instead of loading the entire project, use projection to grab just the publishing settings.
> feat: use projection with publishing request (BUG-1172)

- tests/runtime/lib/Handlers/code/index.unit.ts
Updates tests to reflect changes in code handler. no change to functionality
> fix: failing code handler tests (PL-000)

- backend/api/routers/test.ts
- lib/controllers/test/index.ts
- lib/controllers/test/interface.ts
- https://github.com/voiceflow/XXXXXXXXX/pull/123
- New required environment variables
- Renaming of interfaces (API routes, request/response interface, etc)
- Bug fixes are accompanied by an updated or new test
- New features are accompanied by a new test
> feat: add initial test classification endpoint and validation (PL-845)

- lib/services/classification/predictor.class.ts
- tests/lib/services/classification/predictor.class.unit.ts
> feat: skip NLC results if LLM set (PL-844)

- lib/services/classification/predictor.class.ts
Attempt to improve the debug message for the NLU results to be more in line with other debug messages
> refactor: update nlu debug trace (PL-444)

- lib/services/runtime/handlers/noMatch.ts
repeat the no-reply solution https://github.com/voiceflow/general-runtime/pull/768 for no-match as well.
This ensures consistent behavior.
> fix: add voice to global no match (COR-1712)

- runtime/lib/Handlers/api/utils.ts
the full proxy function to call lambda
> fix: function proxy (PL-927)

- lib/controllers/test/index.ts
- lib/controllers/test/interface.ts
- lib/services/classification/predictor.class.ts
Return LLM error messages in preview endpoint for display in toasts
> feat: llm error messages in preview endpoint (PL-931)

- lib/services/classification/predictor.class.ts
Remove debug trace of NLU confidence as it is redundant
> chore: remove debug trace for NLU confidence (PL-932)

- backend/api/routers/test.ts
- lib/controllers/test/index.ts
- lib/controllers/test/interface.ts
- lib/services/classification/predictor.class.ts
adds an endpoint for test classification
> fix: test classification endpoint (PL-844)

- lib/services/nlu/utils.ts
- lib/services/runtime/handlers/repeat.ts
- package.json
- tests/lib/services/nlu/utils.unit.ts
We no longer support df-es/google assistant projects. It's been deprecated for over 6+ months now.
> fix: remove google-types (COR-1919)
